In [1]:
print('hello world')

hello world


<h1 style='color:red'> Introduction to NumPy</h1>

In [2]:
import numpy as np # importing numpy library

<h2 style='color:red'> Whats is difference between list and array ? </h2>

In [3]:
l1 =  [ 1,2,3,4,5 ]
l2 = [ 4,5,6,7,8]

In [4]:
l1 + l2 

[1, 2, 3, 4, 5, 4, 5, 6, 7, 8]

In [25]:
l1 = [ 

        [ 1,2,3,4],
        [4,5,6,7],
        [8,9,10,11]
    ]
a = np.array(l1)

In [27]:
a

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a[::2,::2]

array([[ 1,  3],
       [ 8, 10]])

In [28]:
a.dtype

dtype('int32')

In [29]:
a.shape

(3, 4)

In [30]:
a.ndim

2

In [31]:
a.size

12

In [7]:
l1[1][2]

6

In [37]:
l1 = [ 
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]

    ]

a = np.array(l1)
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [38]:
a.ndim

3

In [39]:
a.dtype

dtype('int32')

In [40]:
a.shape

(2, 2, 3)

In [41]:
a.size

12

In [11]:
l1[1][0][1]

8

In [12]:
#numpy array

In [13]:
# using built-in data types

In [14]:
l1 = [ var for var in range(10) ]

In [15]:
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
import numpy as np 

a = np.array(l1,dtype=float)

In [17]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
a[::2]

array([0., 2., 4., 6., 8.])

In [20]:
a.ndim

1

In [21]:
a.shape

(10,)

In [22]:
a.size

10

In [23]:
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
